### ISSUE TITLE
set size of modal

### ISSUE THREAD

**Issue by alexeydg** [loveorigami/yii2-modal-ajax#10]
I don't set size of modal window. in single modal set default size is 'sm'.

**Comment by loveorigami** [comment]
Paste our config for widget, please.

**Comment by alexeydg** [comment]
<?php
echo ModalAjax::widget([
    'id' => 'infoModal',
    'header' => '<h3>Заменить товар</h3>',
    'selector' => 'a.change-btn',
    'ajaxSubmit' => true,
    'headerOptions' => ['size' => 'lg'],
    'options' => ['class' => 'header-primary'],
]);?>

**Comment by alexeydg** [comment]
`<?php
echo ModalAjax::widget([
    'id' => 'infoModal',
    'header' => '<h3>Заменить товар</h3>',
    'selector' => 'a.change-btn',
    'ajaxSubmit' => true,
    'headerOptions' => ['size' => 'lg'],
    'options' => ['class' => 'header-primary'],
]);?>`

**Comment by loveorigami** [comment]
see https://www.yiiframework.com/extension/yiisoft/yii2-bootstrap/doc/api/2.2/yii-bootstrap-modal#$size-detail

``` php

echo ModalAjax::widget([ 
'id' => 'infoModal', 
'header' => '<h3>Заменить товар</h3>', 
'selector' => 'a.change-btn',
'ajaxSubmit' => true, 
'size' => ModalAjax::SIZE_LARGE,
'options' => ['class' => 'header-primary'], 
]);

```

**Comment by alexeydg** [comment]
thanks!
