### ISSUE TITLE
Show Modal

### ISSUE THREAD

**Issue by cachepilot** [loveorigami/yii2-modal-ajax#12]
On click to create the button I get an opened modal form,  but can't edit content or close modal.
 If i delete `<div class="modal-backdrop in"></div>` in DOM i can close. I think bug linked with my theme
Need add 
.modal-backdrop {
    /* bug fix - no overlay */
    display: none;
}

**Comment by loveorigami** [comment]
Yiu also try 
```
.modal-backdrop {
/* bug fix - no overlay */
z-index: 1 !important;
}
```
