### ISSUE TITLE
Pjax Reload not working

### ISSUE THREAD

**Issue by websitesa-jefferson** [loveorigami/yii2-modal-ajax#15]
Good morning everyone
I noticed that 'pjaxContainer' => '# grid-company-pjax' is not working.
I checked the ModalAjax.php file on line 199 and added "timeout: false" and the pjax started working again.
Is there another way to make pjax work without passing "timeout: false"?

**Comment by loveorigami** [comment]
Paste your code here, please

**Comment by websitesa-jefferson** [comment]
Sorry for the inconvenience, I managed to solve it, thanks for the attention.
