### ISSUE TITLE
The use of external widgets

### ISSUE THREAD

**Issue by artmarkov** [loveorigami/yii2-modal-ajax#20]
The extension works perfectly. But in the form I use the widget yii\widgets\MaskedInput. But the widget does not work in the modal window. As in Your extension, you can use and connect such widgets. If possible, give an example.

**Comment by loveorigami** [comment]
Have you error in console?

**Comment by artmarkov** [comment]
The console is clean. Interesting fact. I insert the Modal Ajax::widget code into a form that already has fields with widget MaskedInput. If I insert the code before these fields, then everything works, if after, then the widget MaskedInput in the modal window does not work.

**Comment by loveorigami** [comment]
Paste your code, please

**Comment by artmarkov** [comment]
Thanks for the response. Rebuilt the view. Everything works.
