### ISSUE TITLE
Empty model saved

### ISSUE THREAD

**Issue by ghost** [loveorigami/yii2-modal-ajax#5]
Hello! Why my model is empty saved?

**Comment by loveorigami** [comment]
Please, code

**Comment by ghost** [comment]
form:

<div class="users-form">

    <?php $form = ActiveForm::begin();	?>

    <?= $form->field($model, 'username')->textInput(['maxlength' => true]) ?>
    <?= $form->field($model, 'name')->textInput(['maxlength' => true]) ?>
    <?= $form->field($model, 'lastname')->textInput(['maxlength' => true]) ?>
    <?= $form->field($model, 'email')->textInput(['maxlength' => true]) ?>
    <?= $form->field($model, 'status')->textInput(['maxlength' => true]) ?>

    <div class="form-group">
        <?= Html::submitButton('Save', ['class' => 'btn btn-success']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

action:

public function actionCreate() {
		$model = new Users ();
		if ($model->load ( Yii::$app->request->post () )) {
			if ($model->save ()) {
				if (Yii::$app->request->isAjax) {
					Yii::$app->response->format = \yii\web\Response::FORMAT_JSON;
					return ['success' => true];
				}
				return $this->redirect ( [ 'view', 'id' => $model->id] );
			} 
		}
		if (Yii::$app->request->isAjax) {
			return $this->renderAjax ( 'create', [ 
					'model' => $model 
			] );
		} else
			return $this->render ( 'create', [ 
					'model' => $model 
			] );
	}

index:

<div class="users-index">

    <h1><?= Html::encode($this->title) ?></h1>
    <?php // echo $this->render('_search', ['model' => $searchModel]); ?>


   <?php 
	   echo ModalAjax::widget([
	    'id' => 'createUser',
	    'header' => 'New User',
	    'toggleButton' => [
	        'label' => 'New User',
	        'class' => 'btn btn-primary pull-right'
	    ],
	    'url' => Url::to(['/users/create']), // Ajax view with form to load
	    'ajaxSubmit' => true, // Submit the contained form as ajax, true by default
   		'options' => ['class' => 'header-primary'],
   		'autoClose' => true,
	]);

   ?>
   
       <?= GridView::widget([
    		'id' => 'grid-users',
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],

            'id',
            'username',
            'name',
            'lastname',
            'email:email',
            //'status',
            //'created_at',

            ['class' => 'yii\grid\ActionColumn'],
        ],
    ]); ?>
</div>

**Comment by loveorigami** [comment]
Where $model->validate()?

**Comment by ghost** [comment]
Thanx!
