### ISSUE TITLE
Конфиликт скриптов

### ISSUE THREAD

**Issue by webspec2012** [loveorigami/yii2-modal-ajax#7]
При открытии страницы в модальном окне, все внутренние JS инициализируются. Гуд.
Но если потом открывать еще и еще в одном модальном окне, то скрипты из предыдущего запроса конфиликтуют с текущими и вызывают ошибку, честно говоря пока не понял что с этим делать.

**Comment by loveorigami** [comment]
попробуй так
``` js
    $.fn[pluginName] = function (options) {
        return this.each(function () {
           // if (!$.data(this, pluginName)) {
               $.data(this, pluginName, new ModalAjax(this, options));
           // } else {
               // $.data(this, pluginName).initalRequestUrl = options.url;
                //$.data(this, pluginName).selector = options.selector || null;
                //console.log($.data(this, pluginName).initalRequestUrl);
            //}
        });
    };
```

**Comment by webspec2012** [comment]
Спасибо, разобрался.

Выше код не помог, проблема была не в нём.
Проблема была в моих кривых руках.

на странице, которую я открывал в модалальном окне у меня был код:

```
$('#cover-modal').on('kbModalShow', function () {
    setTimeout(initCoverCrop, 500);
});
```

соответственно после закрытия модального окна, это событие оставалось и выполнялось далее при открытии любых других страниц, что вызывало конфликты.

т.е. нельзя вешать события внутри открываемых страниц, это повлечет за собой проблемы.

**Comment by loveorigami** [comment]
Я обычно в таких случаях, перед делигированием события, сначала его очищаю

```
$('#cover-modal').off('kbModalShow').on('kbModalShow', function () {
    setTimeout(initCoverCrop, 500);
});
```
